import { useSession, signIn, signOut } from "next-auth/react"
import { Button, Container, Heading, Text, Flex, Box, Center} from "@chakra-ui/react";
import Head from "next/head";
import MenuBar from "@/components/menuBar";


export default function Home() {
  const { data: session } = useSession();
  if (!session) {
    return (
      <Center>
<Box mt="300px">
        <Text w="100px" mb="20px">Not signed in</Text>
        <Button onClick={() => signIn()} bg="purple.500" w="100px">Sign in</Button>
      </Box>
      </Center>
      
    )
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Flex gap="300px" justify="space-between" align="center">
   <MenuBar/>
        <Box  m="10" justifyItems="center" h="36px">
      <Text>Signed in as {session.user.email} <br /></Text>
      <Button onClick={() => signOut()} h="25px">Sign out</Button>
      </Box>
   </Flex>
        
      
      
      
      
      
      <Container p="20px" centerContent="true">
        <Heading size="3xl">Homepage</Heading>
        <Text mt="3.5" bg="purple.500" color="white">
          Welcome to favorite cities website!<br />
        </Text>
        
      </Container>
    </>
  );
}


