import { Container, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import MenuBar from "@/components/menuBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBar />
      <Container p="20px">
        <Heading size="3xl">Homepage</Heading>
        <Text mt="3.5" bg="purple.500" color="white">
          This is the homepage
        </Text>
      </Container>
    </>
  );
}
